//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjP1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoDadosEntities2 : DbContext
    {
        public BancoDadosEntities2()
            : base("name=BancoDadosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente_Costelaria> Cliente_Costelaria { get; set; }
        public virtual DbSet<tb_pedido_Balcao> tb_pedido_Balcao { get; set; }
        public virtual DbSet<tb_pedidoEncomenda> tb_pedidoEncomenda { get; set; }
        public virtual DbSet<tb_principal> tb_principal { get; set; }
        public virtual DbSet<tb_reserva> tb_reserva { get; set; }
    }
}
