//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjP1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_Balcao
    {
        public int Id { get; set; }
        public string NomeCliente { get; set; }
        public string PedidoB { get; set; }
        public double ValorPedidoB { get; set; }
    }
}
